import "dotenv/config";
import { PrismaPg } from "@prisma/adapter-pg";
import { PrismaClient, Game, Condition } from "@prisma/client";
import bcrypt from "bcryptjs";

const adapter = new PrismaPg({ connectionString: process.env.DATABASE_URL! });
const prisma = new PrismaClient({ adapter });

async function main() {
  console.log("🌱 Seeding CardFellas database...");

  // ── Admin user ────────────────────────────────────────────────────────────
  const adminPassword = await bcrypt.hash("admin1234", 12);
  const admin = await prisma.user.upsert({
    where: { email: "admin@cardfellas.com" },
    update: {},
    create: {
      email: "admin@cardfellas.com",
      firstName: "Store",
      lastName: "Admin",
      password: adminPassword,
      role: "ADMIN",
    },
  });

  const customerPassword = await bcrypt.hash("customer1234", 12);
  await prisma.user.upsert({
    where: { email: "test@cardfellas.com" },
    update: {},
    create: {
      email: "test@cardfellas.com",
      firstName: "Test",
      lastName: "Customer",
      password: customerPassword,
      role: "CUSTOMER",
    },
  });

  console.log("✅ Users seeded");

  // ── MTG Singles ───────────────────────────────────────────────────────────
  const mtgCards = [
    {
      name: "Lightning Bolt",
      setName: "Magic 2011",
      setCode: "M11",
      condition: "NM" as Condition,
      price: 2.5,
      buyCashPrice: 1.0,
      buyCreditPrice: 1.5,
      quantity: 8,
      rarity: "Common",
      colorIdentity: "R",
      isFeatured: true,
      isBuylistFeatured: false,
      imageUrl:
        "https://cards.scryfall.io/normal/front/e/3/e3285gt2-2d3f-4e85-b01f-16b2b5435b1e.jpg",
    },
    {
      name: "Black Lotus",
      setName: "Alpha",
      setCode: "LEA",
      condition: "HP" as Condition,
      price: 8500.0,
      buyCashPrice: 5000.0,
      buyCreditPrice: 6500.0,
      quantity: 1,
      rarity: "Rare",
      colorIdentity: "",
      isFeatured: true,
      isBuylistFeatured: true,
      imageUrl:
        "https://cards.scryfall.io/normal/front/b/d/bd8fa327-dd41-4737-8f19-2cf5eb1f7cdd.jpg",
    },
    {
      name: "Ragavan, Nimble Pilferer",
      setName: "Modern Horizons 2",
      setCode: "MH2",
      condition: "NM" as Condition,
      price: 48.0,
      buyCashPrice: 25.0,
      buyCreditPrice: 35.0,
      quantity: 3,
      rarity: "Mythic",
      colorIdentity: "R",
      isFeatured: true,
      isBuylistFeatured: true,
      imageUrl:
        "https://cards.scryfall.io/normal/front/a/9/a9a54bb4-d5be-4b66-9d17-93399cebf22e.jpg",
    },
    {
      name: "Orcish Bowmasters",
      setName: "The Lord of the Rings",
      setCode: "LTR",
      condition: "NM" as Condition,
      price: 32.0,
      buyCashPrice: 16.0,
      buyCreditPrice: 22.0,
      quantity: 4,
      rarity: "Rare",
      colorIdentity: "B",
      isFeatured: false,
      isBuylistFeatured: true,
      imageUrl:
        "https://cards.scryfall.io/normal/front/5/8/5851f3cb-7f14-4edd-9fc2-5da05ef361fa.jpg",
    },
    {
      name: "Thoughtseize",
      setName: "Theros",
      setCode: "THS",
      condition: "LP" as Condition,
      price: 14.0,
      buyCashPrice: 7.0,
      buyCreditPrice: 10.0,
      quantity: 6,
      rarity: "Rare",
      colorIdentity: "B",
      isFeatured: false,
      isBuylistFeatured: false,
      imageUrl:
        "https://cards.scryfall.io/normal/front/b/0/b0faa7f2-b547-42c4-a810-839da16a2d0c.jpg",
    },
    {
      name: "Force of Will",
      setName: "Alliances",
      setCode: "ALL",
      condition: "MP" as Condition,
      price: 75.0,
      buyCashPrice: 40.0,
      buyCreditPrice: 55.0,
      quantity: 2,
      rarity: "Uncommon",
      colorIdentity: "U",
      isFeatured: false,
      isBuylistFeatured: true,
      imageUrl:
        "https://cards.scryfall.io/normal/front/1/b/1b3e4e08-14bf-4a19-b5b7-74c4f91e5bb6.jpg",
    },
    {
      name: "Counterspell",
      setName: "7th Edition",
      setCode: "7ED",
      condition: "NM" as Condition,
      price: 1.5,
      buyCashPrice: 0.5,
      buyCreditPrice: 0.75,
      quantity: 12,
      rarity: "Common",
      colorIdentity: "U",
      isFeatured: false,
      isBuylistFeatured: false,
      imageUrl:
        "https://cards.scryfall.io/normal/front/1/5/156f2b33-c1c9-4050-a5a0-0b3eed536b71.jpg",
    },
    {
      name: "Liliana of the Veil",
      setName: "Innistrad",
      setCode: "ISD",
      condition: "NM" as Condition,
      price: 45.0,
      buyCashPrice: 22.0,
      buyCreditPrice: 30.0,
      quantity: 2,
      rarity: "Mythic",
      colorIdentity: "B",
      isFeatured: true,
      isBuylistFeatured: false,
      imageUrl:
        "https://cards.scryfall.io/normal/front/f/c/fc80a394-5a46-407e-8b39-8e7e75d6f83b.jpg",
    },
    {
      name: "Wrenn and Six",
      setName: "Modern Horizons",
      setCode: "MH1",
      condition: "NM" as Condition,
      price: 65.0,
      buyCashPrice: 35.0,
      buyCreditPrice: 48.0,
      quantity: 1,
      rarity: "Mythic",
      colorIdentity: "R,G",
      isFeatured: false,
      isBuylistFeatured: true,
      imageUrl:
        "https://cards.scryfall.io/normal/front/3/2/32a06a91-fafd-4e5f-8ac3-b752d4043883.jpg",
    },
    {
      name: "Shivan Dragon",
      setName: "Alpha",
      setCode: "LEA",
      condition: "LP" as Condition,
      price: 120.0,
      buyCashPrice: 60.0,
      buyCreditPrice: 85.0,
      quantity: 1,
      rarity: "Rare",
      colorIdentity: "R",
      isFeatured: false,
      isBuylistFeatured: false,
      imageUrl:
        "https://cards.scryfall.io/normal/front/5/c/5c70ae60-78dc-49e7-b8b8-6f1aee83eed0.jpg",
    },
    {
      name: "Snapcaster Mage",
      setName: "Innistrad",
      setCode: "ISD",
      condition: "NM" as Condition,
      price: 32.0,
      buyCashPrice: 15.0,
      buyCreditPrice: 22.0,
      quantity: 4,
      rarity: "Rare",
      colorIdentity: "U",
      isFeatured: false,
      isBuylistFeatured: false,
      imageUrl:
        "https://cards.scryfall.io/normal/front/2/7/2757e477-c052-4d61-b430-7eca02b8d3d3.jpg",
    },
    {
      name: "Tarmogoyf",
      setName: "Future Sight",
      setCode: "FUT",
      condition: "NM" as Condition,
      price: 28.0,
      buyCashPrice: 14.0,
      buyCreditPrice: 20.0,
      quantity: 3,
      rarity: "Rare",
      colorIdentity: "G",
      isFeatured: false,
      isBuylistFeatured: false,
      imageUrl:
        "https://cards.scryfall.io/normal/front/1/8/18bd50f2-c3ba-4217-a2d0-7b10a4f6c0f5.jpg",
    },
    {
      name: "Mox Diamond",
      setName: "Stronghold",
      setCode: "STH",
      condition: "MP" as Condition,
      price: 290.0,
      buyCashPrice: 150.0,
      buyCreditPrice: 210.0,
      quantity: 1,
      rarity: "Rare",
      colorIdentity: "",
      isFeatured: false,
      isBuylistFeatured: true,
      imageUrl:
        "https://cards.scryfall.io/normal/front/4/5/45e39f64-afdf-4b23-81df-6c20bbdf6a91.jpg",
    },
    {
      name: "Monastery Swiftspear",
      setName: "Khans of Tarkir",
      setCode: "KTK",
      condition: "NM" as Condition,
      price: 3.0,
      buyCashPrice: 1.25,
      buyCreditPrice: 1.75,
      quantity: 10,
      rarity: "Uncommon",
      colorIdentity: "R",
      isFeatured: false,
      isBuylistFeatured: false,
      imageUrl:
        "https://cards.scryfall.io/normal/front/b/5/b5ba4e0a-b0ce-4eff-9adf-6a3e69b1f29f.jpg",
    },
    {
      name: "Atraxa, Praetors' Voice",
      setName: "Commander 2016",
      setCode: "C16",
      condition: "NM" as Condition,
      price: 22.0,
      buyCashPrice: 11.0,
      buyCreditPrice: 15.0,
      quantity: 2,
      rarity: "Mythic",
      colorIdentity: "W,U,B,G",
      isFeatured: false,
      isBuylistFeatured: false,
      imageUrl:
        "https://cards.scryfall.io/normal/front/d/1/d1504523-5908-4c68-9d77-74c5e9a79483.jpg",
    },
  ];

  // ── Pokémon Singles ───────────────────────────────────────────────────────
  const pokemonCards = [
    {
      name: "Charizard Base Set Holo",
      setName: "Base Set",
      setCode: "BS",
      condition: "LP" as Condition,
      price: 380.0,
      buyCashPrice: 200.0,
      buyCreditPrice: 270.0,
      quantity: 1,
      rarity: "Holo Rare",
      colorIdentity: null,
      isFeatured: true,
      isBuylistFeatured: true,
      imageUrl:
        "https://images.pokemontcg.io/base1/4_hires.png",
    },
    {
      name: "Pikachu Illustrator",
      setName: "Promo",
      setCode: "PROMO",
      condition: "NM" as Condition,
      price: 12000.0,
      buyCashPrice: 7000.0,
      buyCreditPrice: 9500.0,
      quantity: 0,
      rarity: "Promo",
      colorIdentity: null,
      isFeatured: false,
      isBuylistFeatured: true,
      imageUrl:
        "https://images.pokemontcg.io/si1/1_hires.png",
    },
    {
      name: "Pikachu VMAX (Rainbow)",
      setName: "Vivid Voltage",
      setCode: "VIV",
      condition: "NM" as Condition,
      price: 45.0,
      buyCashPrice: 22.0,
      buyCreditPrice: 31.0,
      quantity: 3,
      rarity: "Secret Rare",
      colorIdentity: null,
      isFeatured: true,
      isBuylistFeatured: false,
      imageUrl:
        "https://images.pokemontcg.io/swsh4/188_hires.png",
    },
    {
      name: "Mewtwo EX",
      setName: "Next Destinies",
      setCode: "NXD",
      condition: "NM" as Condition,
      price: 18.0,
      buyCashPrice: 9.0,
      buyCreditPrice: 13.0,
      quantity: 5,
      rarity: "Ultra Rare",
      colorIdentity: null,
      isFeatured: false,
      isBuylistFeatured: false,
      imageUrl:
        "https://images.pokemontcg.io/bw4/54_hires.png",
    },
    {
      name: "Umbreon VMAX (Alt Art)",
      setName: "Evolving Skies",
      setCode: "EVS",
      condition: "NM" as Condition,
      price: 95.0,
      buyCashPrice: 50.0,
      buyCreditPrice: 68.0,
      quantity: 2,
      rarity: "Secret Rare",
      colorIdentity: null,
      isFeatured: true,
      isBuylistFeatured: true,
      imageUrl:
        "https://images.pokemontcg.io/swsh7/215_hires.png",
    },
    {
      name: "Rayquaza VMAX",
      setName: "Evolving Skies",
      setCode: "EVS",
      condition: "NM" as Condition,
      price: 38.0,
      buyCashPrice: 19.0,
      buyCreditPrice: 27.0,
      quantity: 4,
      rarity: "Ultra Rare",
      colorIdentity: null,
      isFeatured: false,
      isBuylistFeatured: false,
      imageUrl:
        "https://images.pokemontcg.io/swsh7/217_hires.png",
    },
    {
      name: "Lugia V (Alt Art)",
      setName: "Silver Tempest",
      setCode: "SIT",
      condition: "NM" as Condition,
      price: 72.0,
      buyCashPrice: 38.0,
      buyCreditPrice: 52.0,
      quantity: 2,
      rarity: "Secret Rare",
      colorIdentity: null,
      isFeatured: false,
      isBuylistFeatured: true,
      imageUrl:
        "https://images.pokemontcg.io/swsh12/186_hires.png",
    },
    {
      name: "Blastoise Base Set Holo",
      setName: "Base Set",
      setCode: "BS",
      condition: "MP" as Condition,
      price: 90.0,
      buyCashPrice: 45.0,
      buyCreditPrice: 63.0,
      quantity: 1,
      rarity: "Holo Rare",
      colorIdentity: null,
      isFeatured: false,
      isBuylistFeatured: false,
      imageUrl:
        "https://images.pokemontcg.io/base1/2_hires.png",
    },
    {
      name: "Gardevoir ex (SAR)",
      setName: "Scarlet & Violet",
      setCode: "SVI",
      condition: "NM" as Condition,
      price: 55.0,
      buyCashPrice: 28.0,
      buyCreditPrice: 39.0,
      quantity: 3,
      rarity: "Special Art Rare",
      colorIdentity: null,
      isFeatured: false,
      isBuylistFeatured: false,
      imageUrl:
        "https://images.pokemontcg.io/sv1/86_hires.png",
    },
    {
      name: "Charizard ex (SAR)",
      setName: "Obsidian Flames",
      setCode: "OBF",
      condition: "NM" as Condition,
      price: 88.0,
      buyCashPrice: 45.0,
      buyCreditPrice: 62.0,
      quantity: 2,
      rarity: "Special Art Rare",
      colorIdentity: null,
      isFeatured: true,
      isBuylistFeatured: true,
      imageUrl:
        "https://images.pokemontcg.io/sv3/228_hires.png",
    },
    {
      name: "Venusaur Base Set Holo",
      setName: "Base Set",
      setCode: "BS",
      condition: "LP" as Condition,
      price: 95.0,
      buyCashPrice: 48.0,
      buyCreditPrice: 67.0,
      quantity: 1,
      rarity: "Holo Rare",
      colorIdentity: null,
      isFeatured: false,
      isBuylistFeatured: false,
      imageUrl:
        "https://images.pokemontcg.io/base1/15_hires.png",
    },
    {
      name: "Iono Full Art",
      setName: "Paldea Evolved",
      setCode: "PAL",
      condition: "NM" as Condition,
      price: 42.0,
      buyCashPrice: 21.0,
      buyCreditPrice: 29.0,
      quantity: 4,
      rarity: "Full Art",
      colorIdentity: null,
      isFeatured: false,
      isBuylistFeatured: true,
      imageUrl:
        "https://images.pokemontcg.io/sv2/254_hires.png",
    },
  ];

  // ── Yu-Gi-Oh! Singles ─────────────────────────────────────────────────────
  const yugiohCards = [
    {
      name: "Blue-Eyes White Dragon (LOB 1st Ed)",
      setName: "Legend of Blue Eyes White Dragon",
      setCode: "LOB",
      condition: "LP" as Condition,
      price: 250.0,
      buyCashPrice: 130.0,
      buyCreditPrice: 180.0,
      quantity: 1,
      rarity: "Ultra Rare",
      colorIdentity: null,
      isFeatured: true,
      isBuylistFeatured: true,
      imageUrl:
        "https://images.ygoprodeck.com/images/cards/89631139.jpg",
    },
    {
      name: "Dark Magician (SDY)",
      setName: "Starter Deck: Yugi",
      setCode: "SDY",
      condition: "NM" as Condition,
      price: 8.0,
      buyCashPrice: 3.5,
      buyCreditPrice: 5.0,
      quantity: 6,
      rarity: "Ultra Rare",
      colorIdentity: null,
      isFeatured: false,
      isBuylistFeatured: false,
      imageUrl:
        "https://images.ygoprodeck.com/images/cards/46986414.jpg",
    },
    {
      name: "Ash Blossom & Joyous Spring",
      setName: "Maximum Crisis",
      setCode: "MACR",
      condition: "NM" as Condition,
      price: 6.5,
      buyCashPrice: 3.0,
      buyCreditPrice: 4.5,
      quantity: 8,
      rarity: "Secret Rare",
      colorIdentity: null,
      isFeatured: false,
      isBuylistFeatured: true,
      imageUrl:
        "https://images.ygoprodeck.com/images/cards/14558127.jpg",
    },
    {
      name: "Exodia the Forbidden One (LOB 1st Ed)",
      setName: "Legend of Blue Eyes White Dragon",
      setCode: "LOB",
      condition: "HP" as Condition,
      price: 320.0,
      buyCashPrice: 170.0,
      buyCreditPrice: 240.0,
      quantity: 1,
      rarity: "Ultra Rare",
      colorIdentity: null,
      isFeatured: true,
      isBuylistFeatured: true,
      imageUrl:
        "https://images.ygoprodeck.com/images/cards/33396948.jpg",
    },
    {
      name: "Pot of Greed (MRL 1st Ed)",
      setName: "Magic Ruler",
      setCode: "MRL",
      condition: "MP" as Condition,
      price: 45.0,
      buyCashPrice: 22.0,
      buyCreditPrice: 31.0,
      quantity: 2,
      rarity: "Rare",
      colorIdentity: null,
      isFeatured: false,
      isBuylistFeatured: false,
      imageUrl:
        "https://images.ygoprodeck.com/images/cards/55144522.jpg",
    },
    {
      name: "Nibiru, the Primal Being",
      setName: "Ignition Assault",
      setCode: "IGAS",
      condition: "NM" as Condition,
      price: 5.0,
      buyCashPrice: 2.0,
      buyCreditPrice: 3.0,
      quantity: 10,
      rarity: "Secret Rare",
      colorIdentity: null,
      isFeatured: false,
      isBuylistFeatured: false,
      imageUrl:
        "https://images.ygoprodeck.com/images/cards/27204311.jpg",
    },
    {
      name: "Accesscode Talker",
      setName: "Genesis Impact",
      setCode: "GEIM",
      condition: "NM" as Condition,
      price: 12.0,
      buyCashPrice: 6.0,
      buyCreditPrice: 8.5,
      quantity: 5,
      rarity: "Ultra Rare",
      colorIdentity: null,
      isFeatured: false,
      isBuylistFeatured: true,
      imageUrl:
        "https://images.ygoprodeck.com/images/cards/86066372.jpg",
    },
    {
      name: "Tri-Brigade Ferrijit the Barren Blossom",
      setName: "Lightning Overdrive",
      setCode: "LIOV",
      condition: "NM" as Condition,
      price: 4.0,
      buyCashPrice: 1.75,
      buyCreditPrice: 2.5,
      quantity: 7,
      rarity: "Common",
      colorIdentity: null,
      isFeatured: false,
      isBuylistFeatured: false,
      imageUrl:
        "https://images.ygoprodeck.com/images/cards/99920017.jpg",
    },
    {
      name: "Dark Ruler No More",
      setName: "Eternity Code",
      setCode: "ETCO",
      condition: "NM" as Condition,
      price: 7.0,
      buyCashPrice: 3.25,
      buyCreditPrice: 4.75,
      quantity: 9,
      rarity: "Rare",
      colorIdentity: null,
      isFeatured: false,
      isBuylistFeatured: false,
      imageUrl:
        "https://images.ygoprodeck.com/images/cards/4781655.jpg",
    },
    {
      name: "Pot of Prosperity",
      setName: "Genesis Impact",
      setCode: "GEIM",
      condition: "NM" as Condition,
      price: 28.0,
      buyCashPrice: 14.0,
      buyCreditPrice: 20.0,
      quantity: 4,
      rarity: "Secret Rare",
      colorIdentity: null,
      isFeatured: false,
      isBuylistFeatured: true,
      imageUrl:
        "https://images.ygoprodeck.com/images/cards/1313439.jpg",
    },
  ];

  // ── Sports Cards ──────────────────────────────────────────────────────────
  const sportsCards = [
    {
      name: "Michael Jordan 1986 Fleer #57 RC",
      setName: "1986 Fleer Basketball",
      setCode: "86FLR",
      condition: "LP" as Condition,
      price: 1800.0,
      buyCashPrice: 1000.0,
      buyCreditPrice: 1400.0,
      quantity: 1,
      rarity: "Rookie Card",
      colorIdentity: null,
      isFeatured: true,
      isBuylistFeatured: true,
      imageUrl: null,
    },
    {
      name: "Patrick Mahomes 2017 Panini Prizm RC",
      setName: "2017 Panini Prizm",
      setCode: "17PPR",
      condition: "NM" as Condition,
      price: 320.0,
      buyCashPrice: 170.0,
      buyCreditPrice: 235.0,
      quantity: 1,
      rarity: "Rookie Card",
      colorIdentity: null,
      isFeatured: true,
      isBuylistFeatured: false,
      imageUrl: null,
    },
    {
      name: "Shohei Ohtani 2018 Topps Update RC",
      setName: "2018 Topps Update",
      setCode: "18TU",
      condition: "NM" as Condition,
      price: 95.0,
      buyCashPrice: 50.0,
      buyCreditPrice: 70.0,
      quantity: 2,
      rarity: "Rookie Card",
      colorIdentity: null,
      isFeatured: false,
      isBuylistFeatured: false,
      imageUrl: null,
    },
    {
      name: "Luka Doncic 2018-19 Panini Prizm RC",
      setName: "2018-19 Panini Prizm",
      setCode: "1819PPR",
      condition: "NM" as Condition,
      price: 180.0,
      buyCashPrice: 95.0,
      buyCreditPrice: 132.0,
      quantity: 1,
      rarity: "Rookie Card",
      colorIdentity: null,
      isFeatured: false,
      isBuylistFeatured: true,
      imageUrl: null,
    },
  ];

  // ── Create all products ───────────────────────────────────────────────────
  const allProducts = [
    ...mtgCards.map((c) => ({ ...c, game: "MAGIC" as Game })),
    ...pokemonCards.map((c) => ({ ...c, game: "POKEMON" as Game })),
    ...yugiohCards.map((c) => ({ ...c, game: "YUGIOH" as Game })),
    ...sportsCards.map((c) => ({ ...c, game: "SPORTS" as Game })),
  ];

  for (const card of allProducts) {
    await prisma.product.create({
      data: {
        name: card.name,
        game: card.game,
        setName: card.setName,
        setCode: card.setCode ?? null,
        condition: card.condition,
        price: card.price,
        buyCashPrice: card.buyCashPrice,
        buyCreditPrice: card.buyCreditPrice,
        quantity: card.quantity,
        isFoil: false,
        rarity: card.rarity ?? null,
        colorIdentity: card.colorIdentity ?? null,
        imageUrl: card.imageUrl ?? null,
        isFeatured: card.isFeatured,
        isBuylistFeatured: card.isBuylistFeatured,
      },
    });
  }

  console.log(`✅ ${allProducts.length} products seeded`);

  // ── Events ────────────────────────────────────────────────────────────────
  const now = new Date("2026-06-01");

  const events = [
    {
      title: "Friday Night Magic – Standard",
      game: "MAGIC" as Game,
      date: new Date("2026-06-06T18:30:00"),
      endTime: new Date("2026-06-06T22:00:00"),
      entryFee: 5.0,
      format: "Standard",
      description:
        "Join us every Friday for our weekly Standard tournament. All skill levels welcome! Top 8 players receive store credit prizes.",
      registrationUrl: null,
      ageRestriction: null,
      isActive: true,
    },
    {
      title: "Pokémon TCG League – Saturday",
      game: "POKEMON" as Game,
      date: new Date("2026-06-07T12:00:00"),
      endTime: new Date("2026-06-07T15:00:00"),
      entryFee: 0.0,
      format: "Casual League",
      description:
        "Free weekly Pokémon league play! Earn league stamps and rewards. Great for new players and collectors.",
      registrationUrl: null,
      ageRestriction: null,
      isActive: true,
    },
    {
      title: "Yu-Gi-Oh! Advanced Format Tournament",
      game: "YUGIOH" as Game,
      date: new Date("2026-06-08T13:00:00"),
      endTime: new Date("2026-06-08T17:00:00"),
      entryFee: 10.0,
      format: "Advanced",
      description:
        "Competitive Advanced Format tournament. 3 rounds Swiss + Top 4 cut. Prizes for all Top 4 finishers.",
      registrationUrl: null,
      ageRestriction: null,
      isActive: true,
    },
    {
      title: "MTG Sealed Draft – Duskmourn",
      game: "MAGIC" as Game,
      date: new Date("2026-06-13T14:00:00"),
      endTime: new Date("2026-06-13T18:00:00"),
      entryFee: 25.0,
      format: "Sealed Deck",
      description:
        "Build a 40-card deck from 6 Duskmourn booster packs. 4 rounds Swiss. Prize packs awarded to top finishers.",
      registrationUrl: null,
      ageRestriction: null,
      isActive: true,
    },
    {
      title: "Grand Opening Weekend – Pokémon Pre-Release",
      game: "POKEMON" as Game,
      date: new Date("2026-10-01T11:00:00"),
      endTime: new Date("2026-10-01T15:00:00"),
      entryFee: 30.0,
      format: "Pre-Release",
      description:
        "Celebrate our Grand Opening with an exclusive Pokémon Pre-Release event! Get your hands on the new set before it hits shelves. Every player receives a Pre-Release kit.",
      registrationUrl: null,
      ageRestriction: null,
      isActive: true,
    },
    {
      title: "Grand Opening Weekend – MTG Commander Showdown",
      game: "MAGIC" as Game,
      date: new Date("2026-10-02T13:00:00"),
      endTime: new Date("2026-10-02T18:00:00"),
      entryFee: 10.0,
      format: "Commander",
      description:
        "4-player Commander pods all afternoon during our Grand Opening weekend. Bring your favorite Commander deck and compete for store credit!",
      registrationUrl: null,
      ageRestriction: null,
      isActive: true,
    },
    {
      title: "Friday Night Magic – Draft",
      game: "MAGIC" as Game,
      date: new Date("2026-06-20T18:30:00"),
      endTime: new Date("2026-06-20T22:30:00"),
      entryFee: 15.0,
      format: "Booster Draft",
      description:
        "8-person Booster Draft pod. 3 rounds Swiss. All players keep their drafted cards.",
      registrationUrl: null,
      ageRestriction: null,
      isActive: true,
    },
  ];

  for (const event of events) {
    await prisma.event.create({ data: event });
  }

  console.log(`✅ ${events.length} events seeded`);
  console.log("");
  console.log("🎉 Seed complete!");
  console.log("   Admin login:    admin@cardfellas.com  /  admin1234");
  console.log("   Customer login: test@cardfellas.com   /  customer1234");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
